services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - myapp-network

  myapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
