name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install jq and openssl (dependencies for sync script)
      - name: Install jq and openssl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq openssl

      # Step 3: Make the synchronizer script executable
      - name: Make synchronizer script executable
        run: chmod +x ./synchronizer.sh

      # Step 4: Run Sync Secrets Script
      - name: Run Sync Secrets Script
        run: ./synchronizer.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 6: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 7: Build & Push Docker Image
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ike20743/registerdata-image-new
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
